# List the start up tasks. Learn more: https://www.gitpod.io/docs/configure/workspaces/tasks
tasks:
  - name: Terminal 1
    init: cd  SeleniumProjectPOM/ # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
    command: echo 'open repos'
  - name: Terminal 2
    init: | 
      cd  SeleniumProjectPOM/
      pip install -r rerquirements.txt # runs during prebuild => https://www.gitpod.io/docs/configure/projects/prebuilds
    command: echo 'start script'

# List the ports to expose. Learn more: https://www.gitpod.io/docs/configure/workspaces/ports
ports:
  - name: Frontend
    description: Port 3000 for the frontend
    port: 3000
    onOpen: open-preview

# Learn more from ready-to-use templates: https://www.gitpod.io/docs/introduction/getting-started/quickstart
